version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: notedly_db
    restart: unless-stopped
    command: --wiredTigerCacheSizeGB 1.1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
      - MONGO_INITDB_DATABASE=$DB_NAME
    ports:
      - $PORT:$PORT
    volumes:
      - ./.docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb:/data/db
volumes:
  mongodb:
