version: '3'
services:
  mongo:
    image: mongo
    container_name: notedly_db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_INITDB_ROOT_PASSWORD
    ports:
      - $PORT:$PORT
    volumes:
      - ./mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1.1
